[package]
name = "lucide-floem"
version = "0.1.0"
edition = "2021"

[dependencies]
const_format = { version = "0.2.32", features = ["fmt"] }
floem = {path = "../floem/main"}
lazy_static = "1.4.0"

# floem = { git = "https://github.com/lapce/floem", rev = "341afd255f98ca431e4f615864daa4dbcc057501", default_features = false}
regex = "1.10.3"
